POST http://localhost:3000/api/formSubmit/onBoarding
Content-Type: application/json

{"Full Name":"Darin So","Discord ID - ex: 123123123":"185954567823818752","Miro Email - ex: johndoe@gmail.com":"testemail@gmail.com","GitHub Username - ex: johndoe123":"testname123","What role(s) will you be taking in The Verse?":["Node Management","Researcher","UI/UX"],"What product(s) will you be working on?":["Web Development","WEB3"],"Skills":["Unity","Social Media","Leadership"],"Goal 1:":"get money","Goal 2:":"fuck bitches","Goal 3:":"get more money","Confirm the number of hours you will be working":"12","Start Date":"2023-07-04","End Date":"2023-07-05","Any other questions or comments":""}