POST http://localhost:3000/api/formSubmit/onBoarding
Content-Type: application/json

{"Full Name":"Brandon Cloutier","Discord Username - ex: JohnDoe123 (Case Sensative)":"dino1","Miro Email - ex: johndoe@gmail.com":"enricakumar@gmail.com","GitHub Username - ex: johndoe123":"enricak","What role(s) will you be taking in The Verse?":["Web Developer","Other options"],"What product(s) will you be working on?":["Web Development","Discord & Beyond"],"Skills":["Option 1"],"What are you hoping to learn during this internship at The Verse?":"Professional Development skills and community","Goal 1:":"Learn how to brainstorm and build effective ideas through teamwork and meetings","Goal 2:":"Learn how to independently create programs that help the Verse","Goal 3:":"Meet new people with likeminded values interests and passions!","Confirm the number of hours you will be working":"25","Start Date":"2023-03-15","End Date":"2023-12-31","Any other questions or comments":"Number of hours will reduce in September to around 5 hours a week. End date is unknown. "}

//{"Full Name":"Enrica Kumar","Discord Username - ex: JohnDoe123 (Case Sensative)":"enrica44","Miro Email - ex: johndoe@gmail.com":"enricakumar@gmail.com","GitHub Username - ex: johndoe123":"enricak","What role(s) will you be taking in The Verse?":["Web Developer","Other options"],"What product(s) will you be working on?":["Web Development","Discord & Beyond"],"Skills":["Option 1"],"What are you hoping to learn during this internship at The Verse?":"Professional Development skills and community","Goal 1:":"Learn how to brainstorm and build effective ideas through teamwork and meetings","Goal 2:":"Learn how to independently create programs that help the Verse","Goal 3:":"Meet new people with likeminded values interests and passions!","Confirm the number of hours you will be working":"25","Start Date":"2023-03-15","End Date":"2023-12-31","Any other questions or comments":"Number of hours will reduce in September to around 5 hours a week. End date is unknown. "}
